// apps/customer/types.ts
// Re-export from shared package — update path if using a monorepo resolver
export type {
  Category,
  Product,
  ComboPromotion,
  ComboPromotionItem,
  ComboItemRole,
  AppliedComboMatch,
  ModifierGroup,
  ModifierOption,
  ModifierGroupWithOptions,
  ComboRule,
  Promotion,
  Customer,
  DeliveryAddress,
  Driver,
  Order,
  OrderItem,
  OrderItemWithModifiers,
  OrderEvent,
  CartItem,
  Cart,
  Language,
  OrderStatus,
  DriverStatus,
  StaffRole,
  PaymentMethod,
  PaymentStatus,
  DiscountType,
  PromotionType,
} from '@rms/supabase/types'
